# Generated by Django 3.1.2 on 2020-10-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='This is a test'),
            preserve_default=False,
        ),
    ]
