# Generated by Django 3.1.2 on 2020-10-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Levit Osei-Wusu', max_length=30)),
                ('telephone', models.CharField(max_length=15)),
                ('twitter', models.URLField()),
                ('email', models.EmailField(default='lkanner21@gmail.com', max_length=254)),
                ('github', models.URLField()),
                ('tech_stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_stack', to='portfolio.language')),
            ],
        ),
    ]
